version: '3.8'
services:
  fastify:
    build:
      target: prod
    environment:
      - MAIL_BASE_URL=http://localhost
    image: localhost/fastify-postgresql-back-end
  react:
    build:
      target: prod
    environment:
      - NODE_ENV=production
    image: localhost/react-cra-mui-front-end
    ports:
      - 80:80