apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  selector:
    matchLabels:
      app: react
  replicas: 1
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
        - name: react-cra-mui-front-end
          image: ghcr.io/stetsolutions/react-cra-mui-front-end:v1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              memory: '100Mi'
              cpu: '100m'
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-volume
              mountPath: /etc/nginx/conf.d
      restartPolicy: Always
      volumes:
        - name: nginx-volume
          configMap:
            name: nginx-config-map
